apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: "root"
 namespace: argocd
spec:
 project: default
 source:
  repoURL: "https://github.com/atrakic/argocd-app-of-apps"
  targetRevision: develop # "HEAD"
  path: apps
 destination:
  server: "https://kubernetes.default.svc"
  namespace: "root"
 syncPolicy:
  syncOptions:
   - CreateNamespace=true
  automated:
   selfHeal: true
   prune: true
