name: e2e

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

env:
  APP: guestbook

jobs:
  kind-e2e:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install tools incl. ArgoCD cli
        run: brew bundle

      - name: KinD
        uses: helm/kind-action@v1.5.0
        with:
          config: config/kind.yaml
          cluster_name: kind

      - name: Wait for cluster
        run: |
          kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
          kubectl cluster-info
          kind get clusters

      - name: Setup
        run: |
          make setup
          make port_forward

      - name: Ensure port forward works
        run: curl -fiskL 127.0.0.1:8080

      - name: ArgoCD deploy root
        run: |
          APP=root make sync

      - name: Wait for e2e app to sattle after deployment
        if: false
        run: kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

      - name: Test e2e app
        run: APP=${{ env.APP }} make test

      - name: Get ArgoCD status
        run: make status

      - name: Check if working tree is dirty
        if: always()
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make test and commit changes'
            exit 1
          fi

      - name: Debug failure
        if: failure()
        run: |
          kubectl get all -A
          kubectl get events --sort-by='.metadata.creationTimestamp' -A
