{{- if .Values.logging.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: {{ .Values.logging.targetRevision }}
    chart: {{ .Values.logging.chart }}
    helm:
      parameters:
      - name: gateway.enabled
        value: "false"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.logging.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
