{{- if .Values.nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.nginx.chart }}
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.nginx.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: {{ .Values.nginx.chart }}
    helm:
      parameters:
      - name: controller.kind
        value: daemonset
    repoURL: {{ .Values.nginx.repoURL }}
    targetRevision: {{ .Values.nginx.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
