apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.monitoringCrds.chart }}
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0" # should be lower then monitoring chart
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.monitoringCrds.namespace }}
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.monitoringCrds.repoURL }}
    path: charts/kube-prometheus-stack/crds/
    targetRevision: {{ .Values.monitoringCrds.targetRevision }}
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true # recreate on each version bumps
    automated:
      prune: true
      selfHeal: true
