{{- if .Values.storage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localpath
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
 project: {{ .Values.spec.project }}
 source:
  repoURL: {{ .Values.storage.repoURL }}
  path: deploy/chart/local-path-provisioner
  targetRevision: {{ .Values.storage.targetRevision }}
  helm:
    parameters:
      - name: rbac.create
        value: "true"
      {{- if .Values.storage.local.nodeSelector }}
      - name: nodeSelector
        value: {{ .Values.storage.local.nodeSelector }}
      {{- end }}
 destination:
  server: {{ .Values.spec.destination.server }}
  namespace: {{ .Values.storage.namespace }}
 syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
{{- end }}
