{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.monitoring.namespace }}
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.monitoring.repoURL }}
    targetRevision: {{ .Values.monitoring.targetRevision }}
    #directory:
    #  recurse: true
    helm:
      skipCrds: true
      values: |-
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L140
        alertmanager:
          enabled: false
        # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1963
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            pathType: ImplementationSpecific
            hosts:
              - prometheus.local
        grafana:
            enabled: false
            ingress:
              enabled: false
              ingressClassName: nginx
              pathType: ImplementationSpecific
              hosts:
                - grafana.local
            service:
              type: ClusterIP
            {{- if .Values.logging.enabled }}
            # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L840
            additionalDataSources:
              - name: loki
                type: loki
                url: http://loki.monitoring.svc.cluster.local:3100
           {{- end }}
    chart: {{ .Values.monitoring.chart }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
{{- end }}
